// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVXWwNe5wtFOlMKQ5jP6gjZCNsY7N9P8',
    appId: '1:347950926143:web:8c59608e0a1a50a8d3ab8a',
    messagingSenderId: '347950926143',
    projectId: 'styleme-d7126',
    authDomain: 'styleme-d7126.firebaseapp.com',
    storageBucket: 'styleme-d7126.firebasestorage.app',
    measurementId: 'G-XNCEVBQGG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK4LuZOWdiXMGqZDA6yU58MmzmuP9Oo2E',
    appId: '1:347950926143:android:a222bdb5bed17276d3ab8a',
    messagingSenderId: '347950926143',
    projectId: 'styleme-d7126',
    storageBucket: 'styleme-d7126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA94Y6MSop0-QEft5eiM56Yk8_7-f1Gtqw',
    appId: '1:347950926143:ios:bbfd6dd87003f9e6d3ab8a',
    messagingSenderId: '347950926143',
    projectId: 'styleme-d7126',
    storageBucket: 'styleme-d7126.firebasestorage.app',
    iosBundleId: 'com.example.styleme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA94Y6MSop0-QEft5eiM56Yk8_7-f1Gtqw',
    appId: '1:347950926143:ios:bbfd6dd87003f9e6d3ab8a',
    messagingSenderId: '347950926143',
    projectId: 'styleme-d7126',
    storageBucket: 'styleme-d7126.firebasestorage.app',
    iosBundleId: 'com.example.styleme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGVXWwNe5wtFOlMKQ5jP6gjZCNsY7N9P8',
    appId: '1:347950926143:web:6793828de1843a71d3ab8a',
    messagingSenderId: '347950926143',
    projectId: 'styleme-d7126',
    authDomain: 'styleme-d7126.firebaseapp.com',
    storageBucket: 'styleme-d7126.firebasestorage.app',
    measurementId: 'G-BEG7CHCHTD',
  );
}
